//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTypeLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailTypeLanguage()
        {
            this.EmailAudits = new HashSet<EmailAudit>();
        }
    
        public int Id { get; set; }
        public int EMailTypeId { get; set; }
        public int LanguageId { get; set; }
        public string Subject { get; set; }
        public string TemplateName { get; set; }
    
        public virtual Category EmailType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAudit> EmailAudits { get; set; }
        public virtual Category Language { get; set; }
    }
}
