//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAudit
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EMailFrom { get; set; }
        public string EMailTo { get; set; }
        public Nullable<int> AttachmentNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int EMailTypeLanguageId { get; set; }
        public int CCUsersNumber { get; set; }
        public Nullable<int> ScheduledTaskId { get; set; }
        public string Comment { get; set; }
    
        public virtual EmailTypeLanguage EmailTypeLanguage { get; set; }
        public virtual ScheduledTask ScheduledTask { get; set; }
        public virtual User User { get; set; }
    }
}
