//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.ScheduledTasks = new HashSet<ScheduledTask>();
        }
    
        public int Id { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public Nullable<int> LastModificationUserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string MailSubject { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> TypeUserMailingId { get; set; }
        public bool Active { get; set; }
    
        public virtual Category Type { get; set; }
        public virtual Category TypeUserMailing { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledTask> ScheduledTasks { get; set; }
    }
}
