//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledTask()
        {
            this.EmailAudits = new HashSet<EmailAudit>();
        }
    
        public int Id { get; set; }
        public string CallbackId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public System.DateTime ExpectedExecutionDate { get; set; }
        public Nullable<int> EmailTypeId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> NewsId { get; set; }
    
        public virtual Category EmailType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAudit> EmailAudits { get; set; }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
